version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energy_guard
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/energy_guard
      EXPORT_DIR: /exports
    ports:
      - "8000:8000"
    volumes:
      - ./exports:/exports
      - ./seed_canonical_risks.csv:/app/seed_canonical_risks.csv:ro

volumes:
  db-data:
